### ISSUE TITLE
Error in if (is.na(attr.type)) { : the condition has length > 1

### ISSUE THREAD

**Issue by kbadura3** [bertolt01/asw.cluster#3]
Hi There, 

I am trying to use this package and the earlier issue discussed [Error in if (is.na(attr.type)) { : the condition has length > 1] appears to have re-emerged in version 4.2.1 and up. Is it possible to update the code to address this error.

Thanks!

**Comment by davidyumo** [comment]
Hi There,
I am also encountering the same error "Error in if (is.na(attr.type)) { : the condition has length > 1]" in the same version.

**Comment by bertolt01** [comment]
Just tried with R 4.2.3 on Mac ARM (M1) and on intel: Works as expected. Please update to R 4.2.3 , make sure to re-install asw.cluster from GitHub. Should work as expected.

**Comment by kbadura3** [comment]
Thanks for your prompt response and mentioning that it should be re-installed via github. 

I was using the documentation on the group-faultlines website; which has the package being installed via the group-faultlines website [i.e., (install.packages("asw.cluster", repos="http://www.group-faultlines.org/packages", type="source") ]. The code appears to be running now that it is installed via github!
